name: CI build

on: [push, pull_request]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 5.15.2
        platform:
          - msvc2019

        include:
          - platform: msvc2019
            os: windows-2019
            target: desktop
            make: nmake

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - uses: actions/setup-python@master
        with:
          python-version: '3.10'
          
      - name: Add msbuild to PATH
        if: matrix.platform == 'msvc2019'
        uses: microsoft/setup-msbuild@main
        
      - uses: jurplel/install-qt-action@v3
        id: qt
        with:
          version: ${{matrix.version}}
          target: ${{matrix.target}}
          arch: ${{matrix.arch}}
          tools: ${{matrix.tools}}
          cache: true
          cache-key-prefix: qt

      - name: Configure MSVC (Windows)
        if: contains(matrix.platform, 'msvc')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install QtApng
        run: |
          git clone https://github.com/Skycoder42/QtApng.git
          cd QtApng
          cd src/3rdparty
          chmod +x get_libs.sh
          ./get_libs.sh 1.3.1 1.6.40
          cd ../..
          qmake CONFIG+=install_ok QMAKE_CXXFLAGS+="-fno-sized-deallocation" QT_PLATFORM=${{matrix.platform}}
          ${{matrix.make}}
          ${{matrix.make}} INSTALL_ROOT="${Qt5_DIR}" install

      - name: Install Windows Discord RPC
        if: contains(matrix.os, 'windows')
        env:
            ARCH: ${{ matrix.platform == 'msvc2019' && '64' || '32'}}
        shell: bash
        run: |
          curl -L https://github.com/discordapp/discord-rpc/releases/download/v3.4.0/discord-rpc-win.zip -o discord_rpc.zip
          unzip discord_rpc.zip
          cp ./discord-rpc/win${ARCH}-dynamic/lib/discord-rpc.lib ./lib/
          cp ./discord-rpc/win${ARCH}-dynamic/bin/discord-rpc.dll ./bin/
          cp ./discord-rpc/win${ARCH}-dynamic/include/discord*.h ./include/

      - name: Install Windows BASS
        if: contains(matrix.os, 'windows')
        env:
          ARCH: ${{ matrix.platform == 'msvc2019' && '/x64/' || ''}}
        shell: bash
        run: |
          curl http://www.un4seen.com/files/bass24.zip -o bass.zip
          unzip -d bass -o bass.zip
          cp ./bass/c/${ARCH}bass.lib ./lib/
          cp ./bass/${ARCH}bass.dll ./bin/

          curl http://www.un4seen.com/files/bassmidi24.zip -o bassmidi.zip
          unzip -d bass -o bassmidi.zip
          cp ./bass/c/${ARCH}bassmidi.lib ./lib/
          cp ./bass/${ARCH}bassmidi.dll ./bin/

          curl http://www.un4seen.com/files/bassopus24.zip -o bassopus.zip
          unzip -d bass -o bassopus.zip
          cp ./bass/c/${ARCH}bassopus.lib ./lib/
          cp ./bass/${ARCH}bassopus.dll ./bin/

      - name: qmake
        if: matrix.platform != 'android'
        run: |
          qmake QMAKE_CXXFLAGS+="-fno-sized-deallocation" DEFINES+=DISCORD CONFIG+=install_ok QT_PLATFORM=${{matrix.platform}}

      - name: build
        run: |
          ${{matrix.make}}

      - name: Deploy Windows
        if: contains(matrix.os, 'windows')
        working-directory: ${{github.workspace}}/bin/
        shell: bash
        run: |
          windeployqt --no-quick-import --no-translations --no-virtualkeyboard --no-compiler-runtime --no-webkit2 --no-opengl-sw .
          cp ../QtApng/plugins/imageformats/qapng.dll ./imageformats/
          rm ./imageformats/qtiff.dll
          rm ./imageformats/qjpeg.dll
          rm ./imageformats/qicns.dll
          rm ./imageformats/qico.dll
          rm ./imageformats/qsvg.dll
          rm ./imageformats/qtga.dll
          rm ./imageformats/qwbmp.dll
          rm ./Qt5Svg.dll
          rm -r iconengines
          rm -r bearer
          rm -r base

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: Attorney_Online-${{matrix.os}}-${{matrix.platform}}
          path: ${{github.workspace}}/bin/
